name: lavalink_plugins
description: A package for lavalink that distribute bindings for some lavalin plugins
version: 1.0.0
repository: https://github.com/nyxx-discord/nyxx_lavalink

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  json_annotation: ^4.9.0
  lavalink: any

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
