name: nyxx_lavalink
version: 0.0.0
publish_to: none

repository: https://github.com/nyxx-discord/nyxx_lavalink
issue_tracker: https://github.com/nyxx-discord/nyxx_lavalink/issues

environment:
  sdk: ^3.0.0

dependencies:
  nyxx: ^6.0.3
  lavalink:
    path: ../lavalink

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
