name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [lavalink, nyxx_lavalink, lavalink_plugins]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pubspec-

      - name: "publish ${{ matrix.package }} package to pub.dev"
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          skipTests: true
          force: true
          suppressBuildRunner: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: packages/${{ matrix.package }}

      - name: "Commit release tag"
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{ matrix.package }}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.TAG_RELEASE_TOKEN }}

      - name: "Create Release"
        if: steps.publish.outputs.success
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_RELEASE_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-${{steps.publish.outputs.localVersion}}
          release_name: ${{steps.publish.outputs.localVersion}}
          body: See CHANGELOG.md for the changes in this version.
          draft: false
          prerelease: false
