name: unit tests

on:
  push:
    branches-ignore:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    strategy:
      matrix:
        package: [lavalink, nyxx_lavalink]
  
    steps:
      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pubspec-

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Analyze project source
        working-directory: packages/${{ matrix.package }}
        run: dart analyze

  format:
    name: Format
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    strategy:
      matrix:
        package: [lavalink, nyxx_lavalink]

    steps:
      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pubspec-

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Format
        working-directory: packages/${{ matrix.package }}
        run: dart format --set-exit-if-changed -l 160 ./lib

  tests:
    needs: [ format, analyze ]
    name: Tests
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    strategy:
      matrix:
        package: [lavalink, nyxx_lavalink]
  
    steps:
      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pubspec-

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: dart pub get

      - name: Unit tests
        working-directory: packages/${{ matrix.package }}
        run: dart run test test/unit/**
